CREATE TABLE NT.NOTED(
	 [NT_ID]				DECIMAL NOT NULL
	,[NT_CODE]				NVARCHAR(25) collate SQL_LatIn1_General_Cp850_BIN NOT NULL
	,[TITLE]				NVARCHAR(255) collate SQL_LatIn1_General_Cp850_BIN NOT NULL
	,[CONTENT]				NVARCHAR(255) collate SQL_LatIn1_General_Cp850_BIN  NULL
	,[NT_STS]				NVARCHAR(25)   collate SQL_LatIn1_General_Cp850_BIN  NULL
	,[CREATE_AT]			DATETIME NULL
	,[UPDATE_AT]			DATETIME NULL
	
	,CONSTRAINT PK_EMP_ID	PRIMARY KEY([NT_ID])
) 
GO
ALTER TABLE NT.NOTED ADD  [USER_NAME] NVARCHAR(25)  collate SQL_LatIn1_General_Cp850_BIN  NULL