
ALTER PROCEDURE NT.GEN_NEW_ID(
  @TB_NAME NVARCHAR(255)
 ,@NAME NVARCHAR(255)
 ,@ID DECIMAL OUTPUT
 ,@RT BIT = 0
)   AS
BEGIN
 
	DECLARE
		 @CREATION_DATE DATE = GETDATE()
		,@IDX DECIMAL
		,@SQL NVARCHAR(MAX)
	SET @SQL = N'SELECT @IDX = MAX(CONVERT(DECIMAL, NT.GETNUMERIC(' + @NAME + ', 0))) + 1 FROM ' + @TB_NAME + ' WITH(NOLOCK) '
	EXEC SP_EXECUTESQL @SQL, N'@IDX DECIMAL OUT', @IDX OUT
	SELECT @IDX = ISNULL(@IDX, 1)
	SET @ID = @IDX
	IF @RT = 1
	BEGIN
		SELECT @ID AS ID
	END
END
GO
