ALTER PROCEDURE NT.V_NOTED(
@USER_NAME NVARCHAR(25)
,@FILTER NVARCHAR(225) = NULL

) WITH ENCRYPTION AS
BEGIN
	SET @FILTER = CONCAT(N'%', UPPER(ISNULL(@FILTER, N'')), N'%')
	SELECT 
	 A.NT_ID
	,A.NT_CODE
	,A.TITLE	
	,A.CONTENT
	,A.CREATE_AT
	,A.UPDATE_AT	
	FROM NT.NOTED AS A WITH(NOLOCK)
	WHERE 
	[USER_NAME] = @USER_NAME
	AND NT_STS <> N'DELETE'
	AND(
	NT_CODE LIKE @FILTER
	OR 
	UPPER(TITLE) LIKE @FILTER
	OR
	UPPER(CONTENT) LIKE @FILTER)
	END