CREATE TABLE NT.[USER](
	 [US_ID]				DECIMAL NOT NULL
	,[USER_NAME]			[nvarchar](500) collate SQL_LatIn1_General_Cp850_BIN NOT NULL
	,[PASSWORD]				[varbinary](max)
	,[IS_LOCK]				BIT
	,[LLOG_IN]				DATETIME
	,[IS_ONLINE]			BIT DEFAULT 0
	,[LLOG_OUT]				DATETIME
	,[CREAT_DATE]			DATETIME NOT NULL
    
	,CONSTRAINT PK_USER_US_NAME			Primary Key ([US_ID])
	,CONSTRAINT UK_USER_USER_NAME			UNIQUE([USER_NAME])
	,CONSTRAINT VL_USER_USER_USER_NAME		CHECK([USER_NAME] <> N'')

)
GO

