
CREATE PROCEDURE NT.V_USER
(
	@FILTER NVARCHAR(225)
) WITH ENCRYPTION AS
BEGIN
	SET @FILTER = CONCAT(N'%', UPPER(ISNULL(@FILTER, N'')), N'%')

	SELECT
	US_ID
	,[USER_NAME]
	,[PASSWORD]
	FROM NT.[USER] AS U WITH(NOLOCK)
	WHERE UPPER([USER_NAME]) LIKE @FILTER
END