CREATE PROCEDURE NT.US_LOGIN
(
	@USER_NAME		NVARCHAR(225) = 'TEST'
	,@PASSWORD		NVARCHAR(MAX) =  '123'
) WITH ENCRYPTION AS
BEGIN	
	SELECT 
		 U.US_ID			AS US_ID
		,U.[USER_NAME]		AS [USER_NAME]

	FROM NT.[USER]			AS U WITH(NOLOCK)
	WHERE U.[USER_NAME] = @USER_NAME
		AND U.[PASSWORD]	= @PASSWORD

END

NT.US_LOGIN
	@USER_NAME	 = 'Admin'
	,@PASSWORD	 =  '123'