CREATE PROCEDURE NT.VD_USER
(
	@US_ID DECIMAL 
) WITH ENCRYPTION AS
BEGIN
	SELECT 
	 C.US_ID				AS US_ID			
	,C.[USER_NAME]		    AS [USER_NAME]		
	,C.[PASSWORD]			AS [PASSWORD]				
	
	FROM NT.[USER] AS C WITH(NOLOCK) 
	WHERE C.US_ID = @US_ID

END
