CREATE PROCEDURE NT.VD_NOTED(
@NT_ID DECIMAL
) WITH ENCRYPTION AS
BEGIN
	
	SELECT 
	 A.NT_ID
	,A.NT_CODE
	,A.TITLE	
	,A.CONTENT
	,A.CREATE_AT
	,A.UPDATE_AT	
	FROM NT.NOTED AS A WITH(NOLOCK)
	WHERE NT_ID = @NT_ID
	END